field: 157f1dd3-6182-4ac8-b27f-1119802aa09c # Content Blocks
fieldLayouts:
  451bb070-c3f9-460c-97fe-e82f279bdadf:
    tabs:
      -
        elements:
          -
            fieldUid: e64e80d6-6ff4-417f-817c-9af8c0f34d3e # Audience
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 75e9cb54-9d9f-469f-ba67-8efd8e45a8b1 # Complex Entry
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2f8b915c-c957-4e3b-87f9-e26e50f68bfe # Custom Class
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  2f8b915c-c957-4e3b-87f9-e26e50f68bfe: # Custom Class
    columnSuffix: mlxaxmwx
    contentColumnType: text
    fieldGroup: null
    handle: customClass
    instructions: ''
    name: 'Custom Class'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  75e9cb54-9d9f-469f-ba67-8efd8e45a8b1: # Complex Entry
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: complexEntry
    instructions: ''
    name: 'Complex Entry'
    searchable: true
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  e64e80d6-6ff4-417f-817c-9af8c0f34d3e: # Audience
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: audience
    instructions: ''
    name: Audience
    searchable: true
    settings:
      allowLimit: false
      allowMultipleSources: false
      allowSelfRelations: false
      branchLimit: ''
      limit: null
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: 'group:83e3ba4a-e673-4499-bad1-7b8a299d1fcd' # User type
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Categories
handle: complexBlock
name: 'Complex Block'
sortOrder: 9
