field: 157f1dd3-6182-4ac8-b27f-1119802aa09c # Content Blocks
fieldLayouts:
  737c9845-37bd-4b93-9d31-fd4c3e428a8d:
    tabs:
      -
        elements:
          -
            fieldUid: 98ba90d6-c4e0-4165-8a65-cfe75da45067 # Audience
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: eeea89ef-7322-4496-8d2c-fbfcd389a19a # Heading Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b2855976-f3ec-4276-9d7e-59ddee4961f2 # Heading Level
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 23957a29-2d27-416d-8e13-e090279313f3 # Custom Class
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  98ba90d6-c4e0-4165-8a65-cfe75da45067: # Audience
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: audience
    instructions: 'Choose who can see this'
    name: Audience
    searchable: true
    settings:
      allowLimit: false
      allowMultipleSources: false
      allowSelfRelations: false
      branchLimit: ''
      limit: null
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: 'group:83e3ba4a-e673-4499-bad1-7b8a299d1fcd' # User type
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Categories
  23957a29-2d27-416d-8e13-e090279313f3: # Custom Class
    columnSuffix: kbmzzrla
    contentColumnType: text
    fieldGroup: null
    handle: customClass
    instructions: 'Attach one or more classes to this element separated by spaces'
    name: 'Custom Class'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: 'class-1 class-2'
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b2855976-f3ec-4276-9d7e-59ddee4961f2: # Heading Level
    columnSuffix: gaekoolf
    contentColumnType: string
    fieldGroup: null
    handle: headingLevel
    instructions: 'Choose a level from 2-6 (the page title is Heading Level 1). Sections and sub sections should be nested, e.g., Level 3s will be considered subsections of the previous Level 2.'
    name: 'Heading Level'
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - 'Level 2'
            -
              - value
              - h2
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Level 3'
            -
              - value
              - h3
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Level 4'
            -
              - value
              - h4
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Level 5'
            -
              - value
              - h5
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Level 6'
            -
              - value
              - h6
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  eeea89ef-7322-4496-8d2c-fbfcd389a19a: # Heading Text
    columnSuffix: rmifqbic
    contentColumnType: text
    fieldGroup: null
    handle: headingText
    instructions: ''
    name: 'Heading Text'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: sectionHeading
name: 'Section Heading'
sortOrder: 4
