field: 157f1dd3-6182-4ac8-b27f-1119802aa09c # Content Blocks
fieldLayouts:
  144f3c22-3170-4ad3-8eb2-3d2f12cc6f19:
    tabs:
      -
        elements:
          -
            fieldUid: 0c534d0c-c78f-413b-9525-0435ae1dc0e1 # Audience
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8f0cb1cd-4bd3-41db-85e3-fd7868cf17ff # Table Data
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d02b1c70-59a5-4c84-bbc4-ba09ea0b50d3 # Custom Class
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0c534d0c-c78f-413b-9525-0435ae1dc0e1: # Audience
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: audience
    instructions: ''
    name: Audience
    searchable: true
    settings:
      allowLimit: false
      allowMultipleSources: false
      allowSelfRelations: false
      branchLimit: ''
      limit: null
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: 'group:83e3ba4a-e673-4499-bad1-7b8a299d1fcd' # User type
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Categories
  8f0cb1cd-4bd3-41db-85e3-fd7868cf17ff: # Table Data
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: tableData
    instructions: 'Enter your table data; you can use "null" to merge with the preceding cell, or "blank" to leave a cutout where a cell would be.'
    name: 'Table Data'
    searchable: true
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - ''
                -
                  - handle
                  - ''
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
      maxRows: ''
      minRows: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
  d02b1c70-59a5-4c84-bbc4-ba09ea0b50d3: # Custom Class
    columnSuffix: hquyacjy
    contentColumnType: text
    fieldGroup: null
    handle: customClass
    instructions: 'Attach one or more classes to this element separated by spaces'
    name: 'Custom Class'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: 'class-1 class-2'
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: table
name: Table
sortOrder: 7
