columnSuffix: iktjjput
contentColumnType: text
fieldGroup: a448fcce-1054-44de-ae1d-54931eab4ed5 # Meta
handle: metaRobots
instructions: ''
name: 'Meta Robots'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: 4
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
