fieldLayouts:
  9b32d9a9-a7a7-4255-98a1-8a73316100c8:
    tabs:
      -
        elements:
          -
            fieldUid: 1f6b9b21-7a47-49f5-8b5b-cc04eaf5a698 # GA Key
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Default
        sortOrder: 1
handle: globalMeta
name: 'Global meta'
sortOrder: 1
